name: Approval Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: echo "This is job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Job 2
        run: echo "This is job 2"

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Job 3
        run: echo "This is job 3"

  approval:
    runs-on: ubuntu-latest
    needs: job3
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Collect variable for approval
        run: |
          echo "Please enter the necessary variable:"
          read user_input
          echo "::set-output name=variable::$user_input"

      - name: Perform action with selected variable
        run: |
          selected_variable=${{ steps.approval.outputs.variable }}
          
          # Use the selected_variable in your workflow
          echo "Selected variable: $selected_variable"
          # Perform actions based on the selected variable
