name: Approval Workflow

on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: echo "This is job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Job 2
        run: echo "This is job 2"

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Job 3
        run: echo "This is job 3"

  approval:
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - name: Manual approval
        id: approve
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            const approved = await github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE',
              body: 'Ready for deployment. Please provide the necessary variable as a comment.',
            });

      - name: Wait for approval input
        if: steps.approve.outcome == 'success'
        run: |
          # Logic to wait for approval and extract the variable from the comment
          # For example, using GitHub API to fetch the comment and extract the variable information
          # Handle the selected variable here
