name: Approval Workflow

on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    # Define steps for job1

  job2:
    runs-on: ubuntu-latest
    needs: job1
    # Define steps for job2

  job3:
    runs-on: ubuntu-latest
    needs: job2
    # Define steps for job3

  approval:
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - name: Manual approval
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            const approved = await github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE',
              body: 'Ready for deployment. Please select an option.',
            });
