name: Approval Workflow

on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: echo "This is job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Job 2
        run: echo "This is job 2"

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Job 3
        run: echo "This is job 3"
approval:
    runs-on: ubuntu-latest
    needs: job3
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Get Pull Request Number
        id: pr_number
        run: echo "PR_NUMBER=${{ github.event.client_payload.pull_request_number }}" >> $GITHUB_ENV
      
      - name: Input variable
        id: input_var
        run: |
          echo "Please input the necessary variable."
          echo "::set-output name=variable::${{ github.event.inputs.variable }}"
      
      - name: Perform action with selected variable
        run: |
          pr_number=${{ env.PR_NUMBER }}
          selected_variable=${{ steps.input_var.outputs.variable }}
          
          # Use the selected_variable and pr_number in your workflow
          echo "Selected variable: $selected_variable for PR: $pr_number"
          # Perform actions based on the selected variable