name: Full Approval Workflow

on:
  workflow_dispatch:

jobs:
  approval:
    if: github.event_name == 'workflow_dispatch'
    environment: Sample
    runs-on: ubuntu-latest
    env:
      ENV_VERSION: ${{ secrets.Sample_VERSION }}
    steps:
      - name: Print Version from Sample Environment
        run: |
          echo "VERSION: $VERSION"
