name: Full Approval Workflow

on:
  workflow_dispatch:
    inputs:
      variable:
        description: 'Enter the necessary variable'
        required: true
  pull_request:
    types: [review_requested, review_request_removed, submitted, dismissed]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: echo "This is job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Job 2
        run: echo "This is job 2"

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Job 3
        run: echo "This is job 3"

  approval:
    runs-on: ubuntu-latest
    needs: job3
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action == 'submitted' && github.event.review.state == 'approved')
    steps:
      - name: Collect variable for approval
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Please enter the necessary variable:"
          echo "::set-output name=variable::$user_input"
        else:
          echo "Approved via PR review."

      - name: Perform action with selected variable
        run: |
          selected_variable=${{ github.event.inputs.variable }} # For workflow_dispatch
          selected_variable=${{ steps.approval.outputs.variable }} # For PR review approval
          
          # Use the selected_variable in your workflow
          echo "Selected variable: $selected_variable"
          # Perform actions based on the selected variable
