name: Full Approval Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: echo "This is job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Job 2
        run: echo "This is job 2"

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Job 3
        run: echo "This is job 3"

  approval:
    runs-on: ubuntu-latest
    environment: Sample
    needs: job3
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    steps:
      - name: Trigger Status Check
        run: |
          echo "Pending approval..."
          # Perform necessary steps, such as waiting for an approval

      - name: Perform action after approval
        run: |
          # Perform actions after the approval check
          echo "Approval obtained, performing actions..."
