name: Full Approval Workflow

on:
  workflow_dispatch:

jobs:
  approval:
    if: github.event_name == 'workflow_dispatch'
    environment: Sample
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Version from Sample Environment
        run: |
          echo "VERSION: ${{ secrets.VERSION }}"
