name: Conditional Workflow New

on:
  workflow_dispatch:
    inputs:
      enable_job:
        description: 'Ignore Deploy To QA & UAT'
        required: false
        default: 'false'
        type: boolean

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Conditional Job 1
        run: echo "This is Job 1"

  Deploy-QA:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.enable_job == 'false' }}
    needs: Build
    steps:
      - name: Conditional Job 2
        run: echo "This is Job 2"

  Deploy-UAT:
    runs-on: ubuntu-latest
    needs: Deploy-QA
    steps:
      - name: Conditional Job 3
        run: echo "This is Job 3"
  Deploy-Prod:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Conditional Job 4
        run: echo "This is Job 4"
  Automation-Suite:
    runs-on: ubuntu-latest
    needs: Deploy-UAT
    steps:
      - name: Conditional Job 4
        run: echo "This is Job 4"
