name: New Approval Workflow

on:
  workflow_dispatch:

jobs:
  review_environment:
    environment: Sample
    runs-on: ubuntu-latest
    steps:
      
      - name: Fetch Workflow Run Comments
        id: workflow_run_comments
        if: steps.workflow_run_details.outputs.run_number != ''
        run: |
          RUN_NUMBER="${{ steps.workflow_run_details.outputs.run_number }}"
          COMMENTS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      "https://api.github.com/repos/${{ github.repository }}/actions/runs/${RUN_NUMBER}/timing")

          echo "$COMMENTS" # Output the comments JSON for the specific run
