name: Fetch Workflow Run Comments

on:
  workflow_run:
    workflows: ["Your Workflow Name"]
    types:
      - completed

jobs:
  fetch_comments:
    runs-on: ubuntu-latest
    encironment: Sample
    steps:
      - name: Fetch Workflow Run Details
        id: workflow_run_details
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const workflowRunId = context.payload.workflow_run.id;
            const response = await github.actions.getWorkflowRun({
              owner,
              repo,
              run_id: workflowRunId
            });

            console.log(response.data.run_number);

            // Store required details in outputs
            console.log(`::set-output name=run_number::${response.data.run_number}`);

      - name: Fetch Workflow Run Comments
        id: workflow_run_comments
        if: steps.workflow_run_details.outputs.run_number != ''
        run: |
          RUN_NUMBER="${{ steps.workflow_run_details.outputs.run_number }}"
          COMMENTS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      "https://api.github.com/repos/${{ github.repository }}/actions/runs/${RUN_NUMBER}/logs")

          echo "$COMMENTS" # Output the comments JSON for the specific run

          # You'll need to parse the JSON response to extract comments made by the approver
