name: GCP Instance Management

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        options: ['start', 'stop', 'status']

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  INSTANCE1_IP: '35.221.249.253'
  INSTANCE2_IP: '34.81.51.49'
  INSTANCE3_IP: '35.229.176.129'

jobs:
  manage_instances:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Start/Stop/Status Instances
        run: |
          gcloud compute instances ${{ github.event.inputs.action }} $INSTANCE1_IP $INSTANCE2_IP $INSTANCE3_IP
