# Unified File
name: 'Facadeapi Unified Deployment '
run-name: Deploying  ${{github.ref_name}} Tag to ${{ github.event.inputs.choice }} Environment

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Versions"
        default: 'v2'
        required: true
        type: choice
        options:
          - 'normal'
          - 'v1'
          - 'v2'
          - 'pro'
          - 'consumers'
      choice:
        description: "Environments"
        default: 'QA'
        required: true
        type: choice
        description: Choose a Environment
        options:
        - QA
        - UAT
        - PROD
      Tag:
        description: 'Choose the Tag (Ex: qa-123)'
        required: true


