name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Choose the version (normal, v1, v2, pro)'
        required: true
        default: 'normal'
        # Add other versions as options if needed: options: ['normal', 'v1', 'v2', 'pro']

      environment:
        description: 'Choose the environment (dev, qa, uat, prod)'
        required: true
        default: 'dev'
        # Add other environments as options if needed: options: ['dev', 'qa', 'uat', 'prod']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Service
        run: |
          # Depending on the selected version and environment, perform the deployment
          echo "Deploying version '${{ github.event.inputs.version }}' to '${{ github.event.inputs.environment }}'"
          # Add your deployment commands here based on the chosen version and environment
          # Example: deploy-service --version ${{ github.event.inputs.version }} --environment ${{ github.event.inputs.environment }}
