# Unified File
name: 'Facadeapi Unified Deployment '
run-name: Deploying  ${{github.ref_name}} Tag to ${{ github.event.inputs.choice }} Environment



on:
  workflow_dispatch:
    inputs:
      version:
        description: "Versions"
        default: 'v2'
        required: true
        type: choice
        options:
          - 'normal'
          - 'v1'
          - 'v2'
          - 'pro'
          - 'consumers'
      environment:
        description: "Environment"
        default: 'QA'
        required: true
        type: choice
        options:
          - 'QA'
          - 'UAT'
          - 'PROD'
      # Tag: 
      #   description: 'Tag [ Ex: QA-123 ]'
      #   required: false
      #   type: string
        
jobs:
  Facade-Deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.version }}
    name: 'Build and Deploy to ${{ github.event.inputs.version }}'
    steps:
      - name: Running Command
        run: |
          echo "Version Selected : ${{ github.event.inputs.version }}"
      - name: Running Command
        run: |
          echo "Environment Selected : ${{ github.event.inputs.environment }}"