name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Choose the version (normal, v1, v2, pro)'
        required: true
        default: 'normal'

      environment:
        description: 'Choose the environment (dev, qa, uat, prod)'
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Service
        run: |
          if [ "${{ github.event.inputs.version }}" = "normal" ] && [ "${{ github.event.inputs.environment }}" = "dev" ]; then
            # Deploy 'normal' version to 'dev' environment
            echo "Deploying version 'normal' to 'dev' environment"
            # Add deployment commands for 'normal' version to 'dev' environment
            # Example: deploy-normal-to-dev
          elif [ "${{ github.event.inputs.version }}" = "v2" ] && [ "${{ github.event.inputs.environment }}" = "prod" ]; then
            # Deploy 'v2' version to 'prod' environment
            echo "Deploying version 'v2' to 'prod' environment"
            # Add deployment commands for 'v2' version to 'prod' environment
            # Example: deploy-v2-to-prod
          else
            echo "No specific deployment action defined for the selected version and environment."
          fi
