# Unified File
name: 'Facadeapi Unified Deployment '
run-name: Deploying  ${{github.ref_name}} Tag to ${{ github.event.inputs.choice }} Environment

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Versions"
        default: 'v2'
        required: true
        type: string
        options:
          - 'normal'
          - 'v1'
          - 'v2'
          - 'pro'
          - 'consumers'
      Target:
        description: "Environments"
        default: 'QA'
        required: true
        type: string
        options:
          - 'qa'
          - 'stage'
          - 'production'

      # environment:
      #   description: "Environments"
      #   default: 'QA'
      #   required: true
      #   type: choice
      #   description: Choose a Environment
      #   options:
      #   - 'qa'
      #   - 'stage'
      #   - 'production'

      # Tag:
      #   description: 'Choose the Tag (Ex: qa-123)'
      #   required: true
      #   type: string
      
jobs:
  Facade-Deploy:
    name: 'Deploying  ${{ github.event.inputs.Tag }} Tag to ${{ github.event.inputs.environment }} Env'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.version }}
    steps:
      - name: Running Version Command
        run: |
          echo "Version Selected : ${{ github.event.inputs.version }}"
      - name: Running Environment Command
        run: |
          echo "Environment Selected : ${{ github.event.inputs.environment }}"
      - name: Running Tag Command
        run: |
          echo "Tag Selected : ${{ github.event.inputs.Tag }}"