name: Parameters

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Select an option'
        required: true
        default: 'choice1'
        # You can update the default value to any value from repo.txt

jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - name: Read choices from repo.txt
        run: |
          choices=$(cat repo.txt)
          echo "::set-output name=choices::$choices"

      - name: Extract choice options
        id: extract_choices
        run: |
          choices="$INPUT_CHOICE"
          echo "Choices: $choices"
          choices_array=($choices)
          for choice in "${choices_array[@]}"; do
            echo "::set-output name=choice::$choice"
          done

      - name: Run based on choice
        run: |
          selected_choice="${{ steps.extract_choices.outputs.choice }}"
          echo "Selected choice: $selected_choice"
          # Perform actions based on the selected_choice
