name: Parameters  

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: 'Path to the file with options'
        required: false
        default: 'repo.txt' # Default file path if not provided during manual dispatch

jobs:
  dynamic_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read options from file
        id: read-options
        run: |
          FILE_PATH=${{ github.event.inputs.file_path }}
          OPTIONS=$(<"$FILE_PATH")
          echo "::set-output name=options::$OPTIONS"

      - name: Choose input dynamically
        id: choose-input
        run: |
          OPTIONS_ARRAY=(${{ steps.read-options.outputs.options }})
          for option in "${OPTIONS_ARRAY[@]}"; do
            echo "::add-mask::$option" # Mask the options if sensitive
            echo "Available option: $option"
            # Use the options to perform actions or set dynamic inputs
            # For example, set environment variables or inputs for subsequent steps
            echo "INPUT_OPTION=$option" >> $GITHUB_ENV
          done

      # Use the dynamically chosen input in subsequent steps
      - name: Next Step
        run: |
          echo "Using dynamically chosen input: $INPUT_OPTION"
          # Perform actions using the dynamically chosen input
