name: Sec

on:
  workflow_dispatch:
  
jobs:
  job1:
    env: 
      mykey: ${{ secrets.QA_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Create File
        run: touch key.txt
      - name: Conditional Job 1
        run: echo $mykey > key.txt
      - name: writing
        run: cat key.txt
      
