name: Runners Test 2

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-container-runner
    steps:
      - name: Conditional Job 2
        run: echo "This is Job 2"

      - name: Sleep for 10 seconds
        run: sleep 20
