name: 'TN Workflow dev'

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Choose a Environment
        options:
        - DEV
        - STG

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EKS_CLUSTERNAME: ${{ if eq(matrix.choice, 'DEV') }}dev-eks${{ else }}staging-eks${{ endif }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: echo "Setting up environment - ${{ github.event.inputs.choice }}"
      - name : Read Cluster
        run: |
          echo "EKS_CLUSTERNAME is $EKS_CLUSTERNAME"
     
      # Add more steps for your build process as needed
