name: Conditional Workflow

on:
  workflow_dispatch:
    inputs:
      enable_job:
        description: 'Enable Job 2'
        required: false
        default: 'false'
        type: boolean

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Conditional Job 1
        run: echo "This is Job 1"
      
  job2:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.enable_job == 'true' }}
    steps:
      - name: Conditional Job 2
        run: echo "This is Job 2"

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Conditional Job 3
        run: echo "This is Job 3"
