name: 'TN Workflow dev'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose an Environment'
        default: 'DEV'
        options:
          - DEV
          - STG
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: echo "Setting up environment: ${{ github.event.inputs.environment }}"
