name: 'TN Workflow dev'

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Choose a Environment
        options:
        - DEV
        - STG

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: echo "Setting up environment - ${{ github.event.inputs.choice }}"

      # Add more steps for your build process as needed
