name: 'TN Workflow dev'

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Choose a Environment
        options:
        - DEV
        - STG

jobs:
  build:
    runs-on: ubuntu-latest
    
     
    env:
      EKS_CLUSTERNAME: ${{ github.event.inputs.choice == 'DEV' && 'dev-eks' || github.event.inputs.choice == 'STG' && 'staging-eks' }}
      # number: ${{ github.run_number }}
      # buildnumber: "${{ github.event.inputs.choice == 'DEV' && 'dev-' + github.run_number }} || github.event.inputs.choice == 'STG' && 'stg-' + github.run_number }}"
      buildnumber: "${{ github.event.inputs.choice == 'DEV' && 'dev' || github.event.inputs.choice == 'STG' && 'staging'}}-${{github.run_number}}"
      ASSUME_ROLE: ${{ github.event.inputs.choice == 'DEV' && 'arn:aws:iam::684878003660:role/skyhive-research-development-terrafrom-automation-role' || github.event.inputs.choice == 'STG' && 'arn:aws:iam::027795646707:role/skyhive-staging-qa-terraform-automation-role' || github.event.inputs.choice == 'UAT' && 'arn:aws:iam::027795646707:role/skyhive-staging-qa-terraform-automation-role' }}
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up environment
        run: echo "Setting up environment - ${{ github.event.inputs.choice }}"
        
      - name : Read Cluster
        run: |
          echo "EKS_CLUSTERNAME is $EKS_CLUSTERNAME"

      - name: Print runner name
        run: |
          echo "Runner name is ${{ runner.name }}"
      - name: Print Assume Role
        run: |
          echo "Runner name is $ASSUME_ROLE"
          
    
