name: Release Test

on:
  workflow_dispatch:
    inputs:
      enable_job:
        description: 'Enable Job 2'
        required: false
        default: 'false'
        type: boolean

jobs:
  Build-QA:
    runs-on: ubuntu-latest
    steps:
      - name: Conditional Job 1
        run: echo "This is Job 1"
        env:
          ENABLE_JOB: ${{ github.event.inputs.enable_job }}

  Deploy-UAT:
    runs-on: ubuntu-latest
    needs: Build-QA
    steps:
      - name: Conditional Job 3
        run: echo "This is Job 3"
        env:
          ENABLE_JOB: ${{ needs.Build-QA.outputs.ENABLE_JOB }}
