name: Release Test
on:
  workflow_dispatch:
    inputs:
      enable_build_qa:
        description: 'Enable Build-QA'
        required: false
        default: 'false'
        type: boolean

jobs:
  Build-QA:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.enable_build_qa == 'false' }}
    steps:
      - name: Conditional Job 1
        run: echo "This is Job 1"

  Deploy-UAT:
    runs-on: ubuntu-latest
    needs: Build-QA
    steps:
      - name: Conditional Job 3
        run: echo "This is Job 3"
        env:
          PARAMETER_FOR_UAT: "some_value"

  Automation-Suite:
    runs-on: ubuntu-latest
    needs: Deploy-UAT
    steps:
      - name: Conditional Job 4
        run: echo "This is Job 4"
        env:
          PARAMETER_FOR_SUITE: "another_value"
